name: simple_ollama_chat
description: "A simple ollama chat app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.2 # Untuk membuka galeri foto
  shared_preferences: ^2.3.2 # Untuk menyimpan data foto yang dipilih

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
