name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: true

      - name: Generate Flutter Project & Build
        run: |
          # 1. Buat kerangka proyek flutter baru bernama "my_app" khusus untuk Android
          flutter create my_app --platforms android
          
          # 2. Timpa file bawaan dengan kode main.dart dan pubspec.yaml milik kita
          cp pubspec.yaml my_app/
          cp -r lib/ my_app/
          
          # 3. Masuk ke folder aplikasi, ambil dependensi, lalu rakit APK
          cd my_app
          flutter pub get
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # Ambil file APK dari dalam folder my_app yang baru saja dibuat
          path: my_app/build/app/outputs/flutter-apk/app-release.apk
